name: Build and Test

on: 
  workflow_dispatch:
  push:
    paths:
      - "src/Transmitly.ChannelProvider.MailKit/**"
jobs:
  build_test_deploy_channel_provider:
    uses: transmitly/transmitly/blob/main/.github/workflows/build-and-deploy-channel-provider.yml@main
    with: 
      secrets: inherit
      channelProviderName: Transmitly.ChannelProvider.MailKit
